name: "Lint PR"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# name: Conventional Commits

# on:
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     name: Conventional Commits
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - uses: webiny/action-conventional-commits@v1.1.0
        # optional, required for private repos
        # with:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}