name: "Lint PR"

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review, labeled, synchronize]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true